### ISSUE TITLE
Player 2 L2/LT trigger freezing game

### ISSUE THREAD

**Issue by Hamooson** [WinterSquire/AlphaRing#12]
Thanks for the mod, this has been crazy fun. Just having a small issue where when player 2 uses LT in the campaign it simultaneously switches between classic and remastered and freezes the game. Pausing and unpausing resolves the issue. Current workaround has been remapping the grenade button, but the trigger still causes freezing.

**Comment by WinterSquire** [comment]
Did this only happen in H1 with 2 splitscreen players?

**Comment by WinterSquire** [comment]
[Solved](https://github.com/WinterSquire/AlphaRing/releases/tag/1.0.81)
This only occurs in H1 when the number of inputs exceeds the actual number of players in game.
This happens because the game's input function retrieves input for 4 players each time, but the actual number of players might be less than 4. As a result, inputs for non-existent players can lead to this issue.
